# CHARACTER CONSTANTS
POWER = 100
LEVEL = 1
XP = 0

# WEAPON CONSTANTS
ALLOWED_WEAPONS = ['Сапфировое копье',
                   'Латунный меч',
                   'Ядовитый кинжал',
                   'Алмазный топор',
                    ]

# RAGE MODE CONSTANTS
RAGE_SUCCESS_RATE = 0.5

# HEALTH CONSTANS
MAX_HEALTH = 100
POISONED_HEALTH = 5
NO_POWER_FINE = 5
NO_POWER_POISONED_FINE = 15


# POWER CONSTANTS
BASE_POWER_COST = 5
RAGE_POWER_COST = 30
UNSUCCESS_POWER_ATACK_COST = 0.5



# BATTLE / FIGHT CONSTANTS
ROUND_TIMEOUT = 25
DAMAGE_MULTIPLIER = 5
RANDOM_DAMAGE_MIN = 0.6
RANDOM_DAMAGE_MAX = 1.2
NO_POWER_DAMAGE = 0.5
POISONED_ATTACK = 0.75

# XP - CONSTANTS
MIN_XP_REWARD = 5
